### ISSUE TITLE
Agregar atributos adicionales a las entidades existentes

### ISSUE THREAD

**Issue by nsampi** [datosgobar/georef-ar-etl#117]
**Provincias**

+ *nombre_largo* ("Provincia de...")
+ *categoria*: Tipo de jurisdicción (gna)
+ *id_iso3166-2*: ID de acuerdo a la iso 3166-2:AR.
+ *nombre_iso3166-2*: Nombre de acuerdo a la iso 3166-2:AR.
+ *abreviatura*: Abreviatura de IGN.
+ *fuente* (sag)

**Departamentos**

+ *nombre_largo*
+ *categoria*: Tipo de jurisdicción (gna)
+ *fuente* (sag)

**Municipios**

+ *nombre_largo*
+ *categoria*: Tipo de jurisdicción (gna)
+ *fuente* (sag)

**Localidades**

+ *fuente* (sag)
+ Cambiar nombre "tipo" a "categoria"

**Calles**

+ *localidad_id* (codloc)

**Comment by mcardozo** [comment]
Adjunto los modelos para cada entidad teniendo presente los nuevos atributos.
![model](https://user-images.githubusercontent.com/17284028/50783694-586f8080-128a-11e9-9f6e-8e409698f2f7.png)

**Comment by nsampi** [comment]
Agregar el campo `source` a la tabla  `Road`

**Comment by federicotdn** [comment]
Cambio: campo `nombre_largo` a `nombre_completo`.

**Comment by federicotdn** [comment]
@nsampi investigar municipios con campo `categoria` nulo.

**Comment by mcardozo** [comment]
Actualizo el modelo según lo conversado.

![model](https://user-images.githubusercontent.com/17284028/51050406-78b37e00-15af-11e9-9b84-a51847d6e6f0.png)

**Comment by mcardozo** [comment]
Se agregaron los campos adicionales que se describen en el modelo y se agregaron dichos atributos en la generación de los archivos de salida.

Para las entidades de País y Provincia se agregaron los atributos _iso código_ e _iso nombre_. Para más información sobre la fuente y cruce de los datos ver el _issue_ #124.

**Importante**
Al ejecutar la migraciones con _Django_ se deben correr las siguientes queries previamente:

```sql
SELECT id FROM geo_admin_department WHERE geom ISNULL; 
DELETE FROM geo_admin_settlement WHERE department_id = <id>; -- Obtengo el id de la query anterior
DELETE FROM geo_admin_department WHERE geom ISNULL;
```

**Comment by nsampi** [comment]
@federicotdn @mcardozo deberíamos quitar las tres localidades que aparecen en el endpoint municipio con campo `categoria` nulo ya que son localidades simples y no son gobiernos locales.

**Comment by federicotdn** [comment]
[x] - Cambiar atributo `pais` a un objeto.
[x] - Revisar los códigos de los países.
