### ISSUE TITLE
Intersecciones de calles

### ISSUE THREAD

**Issue by nsampi** [datosgobar/georef-ar-etl#130]
Agregar a la API la funcionalidad de preguntarle por una intersección y que devuelva un punto (lat long) a partir de los índices de ElasticSearch.

**Comment by federicotdn** [comment]
Crear nuevo activo de datos de intersecciones de vías de circulación, para todo el país. En casos donde las vías intersecten en más de un punto, utilizar el centroide.

**Comment by mcardozo** [comment]
Tareas pendientes:  
- [ ] _En casos donde las vías intersecten en más de un punto, utilizar el centroide_
- [ ] No ignorar calles con nombre 'CALLE S N'

**Comment by mcardozo** [comment]
Se completaron las tareas pendientes. Las modificaciones fueron agregadas al rama `developmente`.

cc @federicotdn.
